'use client';

// import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import React from 'react';
import { SettingsProvider, useSettings } from '../context/SettingsContext';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';

const getTheme = (mode: 'light' | 'dark') =>
  createTheme({
    palette: {
      mode,
      primary: {
        main: mode === 'light' ? '#6D4C41' : '#A1887F',
      },
      secondary: {
        main: mode === 'light' ? '#A1887F' : '#8D6E63',
      },
      background: {
        default: mode === 'light' ? '#F5F5DC' : '#121212',
        paper: mode === 'light' ? '#FFFFFF' : '#1E1E1E',
      },
    },
    typography: {
      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
    },
  });

function AppThemeWrapper({ children }: { children: React.ReactNode }) {
  const { darkMode } = useSettings();
  const theme = getTheme(darkMode ? 'dark' : 'light');
  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
}

export default function RootLayout({
  children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={`${raleway.variable}`}>
        <SettingsProvider>
          <AppThemeWrapper>
            <CssBaseline />
            {children}
          </AppThemeWrapper>
        </SettingsProvider>
      </body>
    </html>
  );
}
